### ISSUE TITLE
Implement integration with Slurm clusters

### ISSUE THREAD

**Issue by chesnov** [AllenInstitute/All-active-Workflow#24]
The current version only supports PBS cluster, while suggesting that support for BBP5 and NERSC should be available.

**Comment by anirban6908** [comment]
Hi @chesnov 
Sorry for the delay. I pushed an update that should work for slurm clusters. Note you may have to change some configurations (queue, node names) depending on the cluster you are using. Let me know if this resolves your issue.
Thanks
